module.exports = [{
  input  : ['aab'],
  output : 'aba'
}, {
  input  : ['aaab'],
  output : ''
}, {
  input  : ['tndsewnllhrtwsvxenkscbivijfqnysamckzoyfnapuotmdexzkkrpmppttficzerdndssuveompqkemtbwbodrhwsfpbmkafpwyedpcowruntvymxtyyejqtajkcjakghtdwmuygecjncxzcxezgecrxonnszmqmecgvqqkdagvaaucewelchsmebikscciegzoiamovdojrmmwgbxeygibxxltemfgpogjkhobmhwquizuwvhfaiavsxhiknysdghcawcrphaykyashchyomklvghkyabxatmrkmrfsppfhgrwywtlxebgzmevefcqquvhvgounldxkdzndwybxhtycmlybhaaqvodntsvfhwcuhvuccwcsxelafyzushjhfyklvghpfvknprfouevsxmcuhiiiewcluehpmzrjzffnrptwbuhnyahrbzqvirvmffbxvrmynfcnupnukayjghpusewdwrbkhvjnveuiionefmnfxao'],
  output : 'hkhkhkhkhkhkhkhkhkhkhkhkhkhuhuhuhuhuhuhuhuhuhuhuhuhuhuhueueueueueuesesesesesesesesesesesesesesesesesesesexexexexcxcxcxcxcxcxcxcxcxcxcxcxcxcxcpcpcpcpcpcpcpcpcpcpcpcpmpmpmpmpmpmpmrmrmrmrmrmrmrmrmrmrmrmrmrmrmrmrmrmrmgmgvgvgvgvgvgvgvgvgvgvgvgvgvgvgvgvovovovovovovovovonononononononononbnbnbnbnbnbnbnbnbnbnbnbnbnbnbfbftftftftftftftftftftftftftftftftfififififiyiyiyiyiyiyiyiyiyiyiyiydydydydydydydydydydydadadadadazazazazazazazazazazazazazazalalalalwlwlwlwlwlwlwlwjwjwjwjwjwjwjwjwjwjwjwqwqwqkqkqkqkqkqkqkqkq'
}];