name: Auto update README.md

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Generate README.md
        run: |
          head -n 4 README.md > README.md.tmp
          cd scripts
          python generate_readme.py >> ../README.md.tmp
          cd ..
          mv README.md.tmp README.md
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if ! git diff-index --quiet HEAD --; then
              git add .

              last_commit_message=$(git log -1 --pretty=format:%s)
              new_commit_message="auto update readme for [$last_commit_message]"
              git commit -m "$new_commit_message"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
